

const icons = {
  likeIcon:"/assets/likeIcon.svg",
  userPhoto :"/assets/user-photo.svg",
  badge: "/assets/badge.svg",
  checkIcon: "/assets/check-icon.svg",
  close: "/assets/close.svg",
  "down-arrow": "/assets/down-arrow.svg",
  facebook: "/assets/facebook.svg",
  youtube: "/assets/Group 111317.svg",
  "instagram-1": "/assets/instagram 1.svg",
  instagram: "/assets/instagram.svg",
  livelcon: "/assets/livelcon.svg",
  linkedin: "/assets/linkedin.svg",
  link: "/assets/linkf.svg",
  reverifi: "/assets/reverifi.svg",
  "ring-icon": "/assets/ring-icon.svg",
  twitter: "/assets/share-listing-twitter 1.svg",
  shareicon: "/assets/shareicon.svg",
  star: "/assets/star.svg",
  "user-photo": "/assets/user-photo.svg",
  "user-profile": "/assets/user-profile.svg",
  bronze: "/assets/bronze.svg",
  gold: "/assets/gold.svg",
  goldPlus: "/assets/goldPlus.svg",
  silver: "/assets/silver.svg",
  bathroomIcon: "/assets/bathroomIcon.svg",
  bedroomIcon: "/assets/bedroomIcon.svg",
  boldLikeIcon: "/assets/boldLikeIcon.svg",
  cameraIcon: "/assets/camraIcon.svg",
  closedIcon: "/assets/closedIcon.svg",
  GarageIcon: "/assets/GrageIcon.svg",
  leftArrow: "/assets/leftArrow.svg",
  locationIcon: "/assets/locationIcon.svg",
  rightArrow: "/assets/rightArrow.svg",
  saleIcon: "/assets/saleIcon.svg",
  viewIcon: "/assets/viewIcon.svg",
  imageCard1: "/assets/imageCard1.svg",
  imageCard2: "/assets/imageCard2.svg",
  imageCard3: "/assets/imageCard3.svg"
};

export default icons;